-- Seed data for universities table
-- US and Canadian colleges only (all types: National Universities, Liberal Arts, Private, Community Colleges)

INSERT INTO universities (name, country, state) VALUES
-- Ivy League
('Harvard University', 'US', 'MA'),
('Yale University', 'US', 'CT'),
('Princeton University', 'US', 'NJ'),
('Columbia University', 'US', 'NY'),
('University of Pennsylvania', 'US', 'PA'),
('Brown University', 'US', 'RI'),
('Dartmouth College', 'US', 'NH'),
('Cornell University', 'US', 'NY'),

-- Top Private Universities
('Stanford University', 'US', 'CA'),
('Massachusetts Institute of Technology', 'US', 'MA'),
('California Institute of Technology', 'US', 'CA'),
('Duke University', 'US', 'NC'),
('Northwestern University', 'US', 'IL'),
('University of Chicago', 'US', 'IL'),
('Johns Hopkins University', 'US', 'MD'),
('Rice University', 'US', 'TX'),
('Vanderbilt University', 'US', 'TN'),
('Washington University in St. Louis', 'US', 'MO'),
('Emory University', 'US', 'GA'),
('Georgetown University', 'US', 'DC'),
('Carnegie Mellon University', 'US', 'PA'),
('University of Notre Dame', 'US', 'IN'),
('University of Southern California', 'US', 'CA'),
('New York University', 'US', 'NY'),
('Boston University', 'US', 'MA'),
('Boston College', 'US', 'MA'),
('Tufts University', 'US', 'MA'),
('Wake Forest University', 'US', 'NC'),
('Brandeis University', 'US', 'MA'),
('Case Western Reserve University', 'US', 'OH'),
('Northeastern University', 'US', 'MA'),
('Tulane University', 'US', 'LA'),
('University of Rochester', 'US', 'NY'),
('Lehigh University', 'US', 'PA'),
('Rensselaer Polytechnic Institute', 'US', 'NY'),
('George Washington University', 'US', 'DC'),
('Syracuse University', 'US', 'NY'),
('University of Miami', 'US', 'FL'),
('Pepperdine University', 'US', 'CA'),
('Santa Clara University', 'US', 'CA'),
('Villanova University', 'US', 'PA'),
('Stevens Institute of Technology', 'US', 'NJ'),
('Fordham University', 'US', 'NY'),
('Southern Methodist University', 'US', 'TX'),
('Marquette University', 'US', 'WI'),
('Creighton University', 'US', 'NE'),
('Loyola University Chicago', 'US', 'IL'),
('University of San Diego', 'US', 'CA'),
('University of San Francisco', 'US', 'CA'),
('University of Denver', 'US', 'CO'),
('American University', 'US', 'DC'),
('Drexel University', 'US', 'PA'),
('University of the Pacific', 'US', 'CA'),
('Chapman University', 'US', 'CA'),
('Gonzaga University', 'US', 'WA'),
('Loyola Marymount University', 'US', 'CA'),
('Clark University', 'US', 'MA'),
('Worcester Polytechnic Institute', 'US', 'MA'),
('Illinois Institute of Technology', 'US', 'IL'),
('Rochester Institute of Technology', 'US', 'NY'),
('Yeshiva University', 'US', 'NY'),
('University of Dayton', 'US', 'OH'),
('St. Louis University', 'US', 'MO'),
('University of Tulsa', 'US', 'OK'),
('Hofstra University', 'US', 'NY'),
('Adelphi University', 'US', 'NY'),
('The New School', 'US', 'NY'),
('Seton Hall University', 'US', 'NJ'),
('University of Detroit Mercy', 'US', 'MI'),
('Quinnipiac University', 'US', 'CT'),
('Elon University', 'US', 'NC'),
('University of Scranton', 'US', 'PA'),
('Fairfield University', 'US', 'CT'),
('Providence College', 'US', 'RI'),
('University of Hartford', 'US', 'CT'),
('Sacred Heart University', 'US', 'CT'),
('DePaul University', 'US', 'IL'),
('Duquesne University', 'US', 'PA'),
('St. John''s University', 'US', 'NY'),

-- Top Public Universities (National Universities)
('University of California, Berkeley', 'US', 'CA'),
('University of California, Los Angeles', 'US', 'CA'),
('University of Michigan', 'US', 'MI'),
('University of Virginia', 'US', 'VA'),
('University of North Carolina at Chapel Hill', 'US', 'NC'),
('Georgia Institute of Technology', 'US', 'GA'),
('University of Texas at Austin', 'US', 'TX'),
('University of Wisconsin-Madison', 'US', 'WI'),
('University of Illinois Urbana-Champaign', 'US', 'IL'),
('University of Washington', 'US', 'WA'),
('University of Florida', 'US', 'FL'),
('Ohio State University', 'US', 'OH'),
('Penn State University', 'US', 'PA'),
('Purdue University', 'US', 'IN'),
('University of Maryland, College Park', 'US', 'MD'),
('University of Minnesota', 'US', 'MN'),
('University of California, San Diego', 'US', 'CA'),
('University of California, Davis', 'US', 'CA'),
('University of California, Santa Barbara', 'US', 'CA'),
('University of California, Irvine', 'US', 'CA'),
('University of California, Santa Cruz', 'US', 'CA'),
('University of California, Riverside', 'US', 'CA'),
('University of California, Merced', 'US', 'CA'),
('Texas A&M University', 'US', 'TX'),
('Michigan State University', 'US', 'MI'),
('Indiana University Bloomington', 'US', 'IN'),
('University of Colorado Boulder', 'US', 'CO'),
('University of Pittsburgh', 'US', 'PA'),
('Rutgers University', 'US', 'NJ'),
('University of Iowa', 'US', 'IA'),
('University of Arizona', 'US', 'AZ'),
('Arizona State University', 'US', 'AZ'),
('University of Connecticut', 'US', 'CT'),
('University of Massachusetts Amherst', 'US', 'MA'),
('Virginia Tech', 'US', 'VA'),
('North Carolina State University', 'US', 'NC'),
('University of Georgia', 'US', 'GA'),
('Florida State University', 'US', 'FL'),
('University of South Carolina', 'US', 'SC'),
('Clemson University', 'US', 'SC'),
('University of Tennessee', 'US', 'TN'),
('University of Kentucky', 'US', 'KY'),
('University of Alabama', 'US', 'AL'),
('Auburn University', 'US', 'AL'),
('University of Oregon', 'US', 'OR'),
('Oregon State University', 'US', 'OR'),
('University of Utah', 'US', 'UT'),
('University of Nebraska-Lincoln', 'US', 'NE'),
('University of Kansas', 'US', 'KS'),
('University of Oklahoma', 'US', 'OK'),
('University of Missouri', 'US', 'MO'),
('Iowa State University', 'US', 'IA'),
('Colorado State University', 'US', 'CO'),
('University of New Mexico', 'US', 'NM'),
('University of Nevada, Las Vegas', 'US', 'NV'),
('University of Nevada, Reno', 'US', 'NV'),
('University of Hawaii at Manoa', 'US', 'HI'),
('University of Alaska Fairbanks', 'US', 'AK'),
('University of Wyoming', 'US', 'WY'),
('University of Montana', 'US', 'MT'),
('University of Idaho', 'US', 'ID'),
('Boise State University', 'US', 'ID'),
('University of Vermont', 'US', 'VT'),
('University of New Hampshire', 'US', 'NH'),
('University of Maine', 'US', 'ME'),
('University of Rhode Island', 'US', 'RI'),
('University of Delaware', 'US', 'DE'),
('West Virginia University', 'US', 'WV'),
('University of Louisville', 'US', 'KY'),
('University of Cincinnati', 'US', 'OH'),
('Temple University', 'US', 'PA'),
('University at Buffalo', 'US', 'NY'),
('Stony Brook University', 'US', 'NY'),
('Binghamton University', 'US', 'NY'),
('University at Albany', 'US', 'NY'),
('University of Central Florida', 'US', 'FL'),
('University of South Florida', 'US', 'FL'),
('Florida International University', 'US', 'FL'),
('Florida Atlantic University', 'US', 'FL'),
('University of North Texas', 'US', 'TX'),
('Texas Tech University', 'US', 'TX'),
('University of Houston', 'US', 'TX'),
('San Diego State University', 'US', 'CA'),
('San Jose State University', 'US', 'CA'),
('San Francisco State University', 'US', 'CA'),
('California State University, Long Beach', 'US', 'CA'),
('California State University, Fullerton', 'US', 'CA'),
('California State University, Northridge', 'US', 'CA'),
('California State University, Los Angeles', 'US', 'CA'),
('California Polytechnic State University', 'US', 'CA'),
('George Mason University', 'US', 'VA'),
('James Madison University', 'US', 'VA'),
('Old Dominion University', 'US', 'VA'),
('Virginia Commonwealth University', 'US', 'VA'),
('Wayne State University', 'US', 'MI'),
('Western Michigan University', 'US', 'MI'),
('Kent State University', 'US', 'OH'),
('Bowling Green State University', 'US', 'OH'),
('Miami University', 'US', 'OH'),
('Ball State University', 'US', 'IN'),
('Northern Illinois University', 'US', 'IL'),
('Southern Illinois University', 'US', 'IL'),
('University of Illinois Chicago', 'US', 'IL'),

-- New Jersey Schools
('New Jersey Institute of Technology', 'US', 'NJ'),
('Montclair State University', 'US', 'NJ'),
('Rowan University', 'US', 'NJ'),
('The College of New Jersey', 'US', 'NJ'),
('Fairleigh Dickinson University', 'US', 'NJ'),
('Kean University', 'US', 'NJ'),
('William Paterson University', 'US', 'NJ'),
('Stockton University', 'US', 'NJ'),
('Rider University', 'US', 'NJ'),
('New Jersey City University', 'US', 'NJ'),
('Ramapo College of New Jersey', 'US', 'NJ'),

-- Liberal Arts Colleges
('Williams College', 'US', 'MA'),
('Amherst College', 'US', 'MA'),
('Swarthmore College', 'US', 'PA'),
('Wellesley College', 'US', 'MA'),
('Pomona College', 'US', 'CA'),
('Bowdoin College', 'US', 'ME'),
('Middlebury College', 'US', 'VT'),
('Carleton College', 'US', 'MN'),
('Claremont McKenna College', 'US', 'CA'),
('Davidson College', 'US', 'NC'),
('Harvey Mudd College', 'US', 'CA'),
('Haverford College', 'US', 'PA'),
('Colgate University', 'US', 'NY'),
('Hamilton College', 'US', 'NY'),
('Wesleyan University', 'US', 'CT'),
('Vassar College', 'US', 'NY'),
('Colby College', 'US', 'ME'),
('Bates College', 'US', 'ME'),
('Grinnell College', 'US', 'IA'),
('Colorado College', 'US', 'CO'),
('Oberlin College', 'US', 'OH'),
('Barnard College', 'US', 'NY'),
('Bryn Mawr College', 'US', 'PA'),
('Smith College', 'US', 'MA'),
('Mount Holyoke College', 'US', 'MA'),
('Scripps College', 'US', 'CA'),
('Pitzer College', 'US', 'CA'),
('Washington and Lee University', 'US', 'VA'),
('Bucknell University', 'US', 'PA'),
('Lafayette College', 'US', 'PA'),
('Union College', 'US', 'NY'),
('Trinity College', 'US', 'CT'),
('Connecticut College', 'US', 'CT'),
('Kenyon College', 'US', 'OH'),
('Denison University', 'US', 'OH'),
('Macalester College', 'US', 'MN'),
('Reed College', 'US', 'OR'),
('Whitman College', 'US', 'WA'),
('Lewis & Clark College', 'US', 'OR'),
('Occidental College', 'US', 'CA'),
('University of Richmond', 'US', 'VA'),
('Dickinson College', 'US', 'PA'),
('Gettysburg College', 'US', 'PA'),
('Franklin & Marshall College', 'US', 'PA'),
('Muhlenberg College', 'US', 'PA'),
('Skidmore College', 'US', 'NY'),
('Sarah Lawrence College', 'US', 'NY'),
('Bennington College', 'US', 'VT'),
('St. Olaf College', 'US', 'MN'),
('Lawrence University', 'US', 'WI'),
('Beloit College', 'US', 'WI'),
('Knox College', 'US', 'IL'),
('Lake Forest College', 'US', 'IL'),
('Rhodes College', 'US', 'TN'),
('Sewanee: The University of the South', 'US', 'TN'),
('Centre College', 'US', 'KY'),
('DePauw University', 'US', 'IN'),
('Wabash College', 'US', 'IN'),
('Kalamazoo College', 'US', 'MI'),
('Allegheny College', 'US', 'PA'),
('Furman University', 'US', 'SC'),
('Rollins College', 'US', 'FL'),
('Trinity University', 'US', 'TX'),
('Southwestern University', 'US', 'TX'),
('Austin College', 'US', 'TX'),

-- Business Schools (standalone programs)
('Wharton School (UPenn)', 'US', 'PA'),
('Stern School of Business (NYU)', 'US', 'NY'),
('Booth School of Business (UChicago)', 'US', 'IL'),
('Sloan School of Management (MIT)', 'US', 'MA'),
('Haas School of Business (Berkeley)', 'US', 'CA'),
('Ross School of Business (Michigan)', 'US', 'MI'),
('Kellogg School of Management (Northwestern)', 'US', 'IL'),
('Tuck School of Business (Dartmouth)', 'US', 'NH'),
('Fuqua School of Business (Duke)', 'US', 'NC'),
('McCombs School of Business (UT Austin)', 'US', 'TX'),

-- STEM Focus Schools
('Georgia Tech', 'US', 'GA'),
('Rose-Hulman Institute of Technology', 'US', 'IN'),
('Colorado School of Mines', 'US', 'CO'),
('Missouri University of Science and Technology', 'US', 'MO'),
('New Mexico Institute of Mining and Technology', 'US', 'NM'),
('South Dakota School of Mines and Technology', 'US', 'SD'),
('Montana Tech', 'US', 'MT'),

-- CUNY System (New York)
('CUNY Baruch College', 'US', 'NY'),
('CUNY City College', 'US', 'NY'),
('CUNY Hunter College', 'US', 'NY'),
('CUNY Brooklyn College', 'US', 'NY'),
('CUNY Queens College', 'US', 'NY'),
('CUNY John Jay College', 'US', 'NY'),
('CUNY Lehman College', 'US', 'NY'),
('CUNY College of Staten Island', 'US', 'NY'),

-- SUNY System (New York)
('SUNY Geneseo', 'US', 'NY'),
('SUNY New Paltz', 'US', 'NY'),
('SUNY Oswego', 'US', 'NY'),
('SUNY Plattsburgh', 'US', 'NY'),
('SUNY Oneonta', 'US', 'NY'),
('SUNY Cortland', 'US', 'NY'),
('SUNY Fredonia', 'US', 'NY'),
('SUNY Potsdam', 'US', 'NY'),
('SUNY Purchase', 'US', 'NY'),

-- Community Colleges - California
('Santa Monica College', 'US', 'CA'),
('Pasadena City College', 'US', 'CA'),
('De Anza College', 'US', 'CA'),
('Foothill College', 'US', 'CA'),
('Diablo Valley College', 'US', 'CA'),
('Orange Coast College', 'US', 'CA'),
('Irvine Valley College', 'US', 'CA'),
('Glendale Community College', 'US', 'CA'),
('El Camino College', 'US', 'CA'),
('Mt. San Antonio College', 'US', 'CA'),
('College of San Mateo', 'US', 'CA'),
('City College of San Francisco', 'US', 'CA'),
('Saddleback College', 'US', 'CA'),
('Santa Barbara City College', 'US', 'CA'),
('Los Angeles City College', 'US', 'CA'),

-- Community Colleges - New York
('LaGuardia Community College', 'US', 'NY'),
('Borough of Manhattan Community College', 'US', 'NY'),
('Queensborough Community College', 'US', 'NY'),
('Bronx Community College', 'US', 'NY'),
('Kingsborough Community College', 'US', 'NY'),
('Nassau Community College', 'US', 'NY'),
('Suffolk County Community College', 'US', 'NY'),
('Westchester Community College', 'US', 'NY'),

-- Community Colleges - New Jersey
('Bergen Community College', 'US', 'NJ'),
('Middlesex County College', 'US', 'NJ'),
('County College of Morris', 'US', 'NJ'),
('Ocean County College', 'US', 'NJ'),
('Raritan Valley Community College', 'US', 'NJ'),
('Brookdale Community College', 'US', 'NJ'),
('Passaic County Community College', 'US', 'NJ'),
('Hudson County Community College', 'US', 'NJ'),
('Essex County College', 'US', 'NJ'),
('Union County College', 'US', 'NJ'),
('Camden County College', 'US', 'NJ'),
('Mercer County Community College', 'US', 'NJ'),
('Atlantic Cape Community College', 'US', 'NJ'),
('Rowan College at Burlington County', 'US', 'NJ'),
('Rowan College of South Jersey', 'US', 'NJ'),

-- Community Colleges - Texas
('Austin Community College', 'US', 'TX'),
('Houston Community College', 'US', 'TX'),
('Dallas County Community College', 'US', 'TX'),
('Tarrant County College', 'US', 'TX'),
('San Antonio College', 'US', 'TX'),
('Lone Star College', 'US', 'TX'),
('Collin College', 'US', 'TX'),
('El Paso Community College', 'US', 'TX'),

-- Community Colleges - Florida
('Miami Dade College', 'US', 'FL'),
('Broward College', 'US', 'FL'),
('Valencia College', 'US', 'FL'),
('Palm Beach State College', 'US', 'FL'),
('Hillsborough Community College', 'US', 'FL'),
('Santa Fe College', 'US', 'FL'),

-- Community Colleges - Illinois
('College of DuPage', 'US', 'IL'),
('Harper College', 'US', 'IL'),
('Oakton Community College', 'US', 'IL'),
('Moraine Valley Community College', 'US', 'IL'),
('Triton College', 'US', 'IL'),
('City Colleges of Chicago', 'US', 'IL'),

-- Community Colleges - Virginia
('Northern Virginia Community College', 'US', 'VA'),
('Tidewater Community College', 'US', 'VA'),
('J. Sargeant Reynolds Community College', 'US', 'VA'),

-- Community Colleges - Other States
('Maricopa Community College', 'US', 'AZ'),
('Pima Community College', 'US', 'AZ'),
('Portland Community College', 'US', 'OR'),
('Seattle Central College', 'US', 'WA'),
('Bellevue College', 'US', 'WA'),
('Green River College', 'US', 'WA'),
('Montgomery College', 'US', 'MD'),
('Prince George''s Community College', 'US', 'MD'),
('Community College of Denver', 'US', 'CO'),
('Red Rocks Community College', 'US', 'CO'),
('Cuyahoga Community College', 'US', 'OH'),
('Columbus State Community College', 'US', 'OH'),

-- Canada - Ontario
('University of Toronto', 'CA', 'ON'),
('University of Waterloo', 'CA', 'ON'),
('Western University', 'CA', 'ON'),
('Queen''s University', 'CA', 'ON'),
('McMaster University', 'CA', 'ON'),
('York University', 'CA', 'ON'),
('Ryerson University', 'CA', 'ON'),
('University of Ottawa', 'CA', 'ON'),
('Carleton University', 'CA', 'ON'),
('University of Guelph', 'CA', 'ON'),
('Wilfrid Laurier University', 'CA', 'ON'),
('Brock University', 'CA', 'ON'),
('University of Windsor', 'CA', 'ON'),
('Ontario Tech University', 'CA', 'ON'),
('Trent University', 'CA', 'ON'),
('Lakehead University', 'CA', 'ON'),

-- Canada - Quebec
('McGill University', 'CA', 'QC'),
('Université de Montréal', 'CA', 'QC'),
('Concordia University', 'CA', 'QC'),
('Université Laval', 'CA', 'QC'),
('Université de Sherbrooke', 'CA', 'QC'),
('HEC Montreal', 'CA', 'QC'),
('UQAM', 'CA', 'QC'),

-- Canada - British Columbia
('University of British Columbia', 'CA', 'BC'),
('Simon Fraser University', 'CA', 'BC'),
('University of Victoria', 'CA', 'BC'),
('University of Northern British Columbia', 'CA', 'BC'),
('Thompson Rivers University', 'CA', 'BC'),

-- Canada - Alberta
('University of Alberta', 'CA', 'AB'),
('University of Calgary', 'CA', 'AB'),
('University of Lethbridge', 'CA', 'AB'),
('Mount Royal University', 'CA', 'AB'),
('MacEwan University', 'CA', 'AB'),

-- Canada - Other Provinces
('University of Manitoba', 'CA', 'MB'),
('University of Saskatchewan', 'CA', 'SK'),
('University of Regina', 'CA', 'SK'),
('Dalhousie University', 'CA', 'NS'),
('Saint Mary''s University', 'CA', 'NS'),
('Acadia University', 'CA', 'NS'),
('University of New Brunswick', 'CA', 'NB'),
('Memorial University of Newfoundland', 'CA', 'NL'),
('University of Prince Edward Island', 'CA', 'PE'),

-- Canadian Colleges (Community Colleges / Polytechnics)
('Seneca College', 'CA', 'ON'),
('Humber College', 'CA', 'ON'),
('George Brown College', 'CA', 'ON'),
('Sheridan College', 'CA', 'ON'),
('Centennial College', 'CA', 'ON'),
('Conestoga College', 'CA', 'ON'),
('Fanshawe College', 'CA', 'ON'),
('Mohawk College', 'CA', 'ON'),
('Algonquin College', 'CA', 'ON'),
('Durham College', 'CA', 'ON'),
('BCIT', 'CA', 'BC'),
('Douglas College', 'CA', 'BC'),
('Langara College', 'CA', 'BC'),
('SAIT', 'CA', 'AB'),
('NAIT', 'CA', 'AB'),
('Red River College', 'CA', 'MB'),
('Saskatchewan Polytechnic', 'CA', 'SK'),
('Nova Scotia Community College', 'CA', 'NS'),
('NBCC', 'CA', 'NB'),
('Cégep du Vieux Montréal', 'CA', 'QC'),
('Dawson College', 'CA', 'QC'),
('Vanier College', 'CA', 'QC'),
('John Abbott College', 'CA', 'QC'),

-- Other entry for unlisted schools
('Other (please specify in message)', 'OTHER', NULL)

ON CONFLICT (name) DO NOTHING;
