-- Seed data for universities table
-- Top US universities + select international schools

INSERT INTO universities (name, country, state) VALUES
-- Ivy League
('Harvard University', 'US', 'MA'),
('Yale University', 'US', 'CT'),
('Princeton University', 'US', 'NJ'),
('Columbia University', 'US', 'NY'),
('University of Pennsylvania', 'US', 'PA'),
('Brown University', 'US', 'RI'),
('Dartmouth College', 'US', 'NH'),
('Cornell University', 'US', 'NY'),

-- Top Private Universities
('Stanford University', 'US', 'CA'),
('Massachusetts Institute of Technology', 'US', 'MA'),
('California Institute of Technology', 'US', 'CA'),
('Duke University', 'US', 'NC'),
('Northwestern University', 'US', 'IL'),
('University of Chicago', 'US', 'IL'),
('Johns Hopkins University', 'US', 'MD'),
('Rice University', 'US', 'TX'),
('Vanderbilt University', 'US', 'TN'),
('Washington University in St. Louis', 'US', 'MO'),
('Emory University', 'US', 'GA'),
('Georgetown University', 'US', 'DC'),
('Carnegie Mellon University', 'US', 'PA'),
('University of Notre Dame', 'US', 'IN'),
('University of Southern California', 'US', 'CA'),
('New York University', 'US', 'NY'),
('Boston University', 'US', 'MA'),
('Boston College', 'US', 'MA'),
('Tufts University', 'US', 'MA'),
('Wake Forest University', 'US', 'NC'),
('Brandeis University', 'US', 'MA'),
('Case Western Reserve University', 'US', 'OH'),
('Northeastern University', 'US', 'MA'),
('Tulane University', 'US', 'LA'),
('University of Rochester', 'US', 'NY'),
('Lehigh University', 'US', 'PA'),
('Rensselaer Polytechnic Institute', 'US', 'NY'),
('George Washington University', 'US', 'DC'),
('Syracuse University', 'US', 'NY'),
('University of Miami', 'US', 'FL'),
('Pepperdine University', 'US', 'CA'),
('Santa Clara University', 'US', 'CA'),
('Villanova University', 'US', 'PA'),
('Stevens Institute of Technology', 'US', 'NJ'),

-- Top Public Universities
('University of California, Berkeley', 'US', 'CA'),
('University of California, Los Angeles', 'US', 'CA'),
('University of Michigan', 'US', 'MI'),
('University of Virginia', 'US', 'VA'),
('University of North Carolina at Chapel Hill', 'US', 'NC'),
('Georgia Institute of Technology', 'US', 'GA'),
('University of Texas at Austin', 'US', 'TX'),
('University of Wisconsin-Madison', 'US', 'WI'),
('University of Illinois Urbana-Champaign', 'US', 'IL'),
('University of Washington', 'US', 'WA'),
('University of Florida', 'US', 'FL'),
('Ohio State University', 'US', 'OH'),
('Penn State University', 'US', 'PA'),
('Purdue University', 'US', 'IN'),
('University of Maryland, College Park', 'US', 'MD'),
('University of Minnesota', 'US', 'MN'),
('University of California, San Diego', 'US', 'CA'),
('University of California, Davis', 'US', 'CA'),
('University of California, Santa Barbara', 'US', 'CA'),
('University of California, Irvine', 'US', 'CA'),
('Texas A&M University', 'US', 'TX'),
('Michigan State University', 'US', 'MI'),
('Indiana University Bloomington', 'US', 'IN'),
('University of Colorado Boulder', 'US', 'CO'),
('University of Pittsburgh', 'US', 'PA'),
('Rutgers University', 'US', 'NJ'),
('University of Iowa', 'US', 'IA'),
('University of Arizona', 'US', 'AZ'),
('Arizona State University', 'US', 'AZ'),
('University of Connecticut', 'US', 'CT'),
('University of Massachusetts Amherst', 'US', 'MA'),
('Virginia Tech', 'US', 'VA'),
('North Carolina State University', 'US', 'NC'),
('University of Georgia', 'US', 'GA'),
('Florida State University', 'US', 'FL'),
('University of South Carolina', 'US', 'SC'),
('Clemson University', 'US', 'SC'),
('University of Tennessee', 'US', 'TN'),
('University of Kentucky', 'US', 'KY'),
('University of Alabama', 'US', 'AL'),
('Auburn University', 'US', 'AL'),
('University of Oregon', 'US', 'OR'),
('Oregon State University', 'US', 'OR'),
('University of Utah', 'US', 'UT'),
('University of Nebraska-Lincoln', 'US', 'NE'),
('University of Kansas', 'US', 'KS'),
('University of Oklahoma', 'US', 'OK'),
('University of Missouri', 'US', 'MO'),
('Iowa State University', 'US', 'IA'),
('Colorado State University', 'US', 'CO'),

-- Liberal Arts Colleges
('Williams College', 'US', 'MA'),
('Amherst College', 'US', 'MA'),
('Swarthmore College', 'US', 'PA'),
('Wellesley College', 'US', 'MA'),
('Pomona College', 'US', 'CA'),
('Bowdoin College', 'US', 'ME'),
('Middlebury College', 'US', 'VT'),
('Carleton College', 'US', 'MN'),
('Claremont McKenna College', 'US', 'CA'),
('Davidson College', 'US', 'NC'),
('Harvey Mudd College', 'US', 'CA'),
('Haverford College', 'US', 'PA'),
('Colgate University', 'US', 'NY'),
('Hamilton College', 'US', 'NY'),
('Wesleyan University', 'US', 'CT'),
('Vassar College', 'US', 'NY'),
('Colby College', 'US', 'ME'),
('Bates College', 'US', 'ME'),
('Grinnell College', 'US', 'IA'),
('Colorado College', 'US', 'CO'),
('Oberlin College', 'US', 'OH'),
('Barnard College', 'US', 'NY'),
('Bryn Mawr College', 'US', 'PA'),
('Smith College', 'US', 'MA'),
('Mount Holyoke College', 'US', 'MA'),

-- Business/Finance Focus
('Wharton School (UPenn)', 'US', 'PA'),
('Stern School of Business (NYU)', 'US', 'NY'),
('Booth School of Business (UChicago)', 'US', 'IL'),
('Sloan School of Management (MIT)', 'US', 'MA'),
('Haas School of Business (Berkeley)', 'US', 'CA'),
('Ross School of Business (Michigan)', 'US', 'MI'),
('Kellogg School of Management (Northwestern)', 'US', 'IL'),
('Tuck School of Business (Dartmouth)', 'US', 'NH'),
('Fuqua School of Business (Duke)', 'US', 'NC'),
('McCombs School of Business (UT Austin)', 'US', 'TX'),

-- STEM Focus
('Georgia Tech', 'US', 'GA'),
('Rose-Hulman Institute of Technology', 'US', 'IN'),
('Worcester Polytechnic Institute', 'US', 'MA'),
('Rochester Institute of Technology', 'US', 'NY'),
('Illinois Institute of Technology', 'US', 'IL'),
('Drexel University', 'US', 'PA'),
('Colorado School of Mines', 'US', 'CO'),

-- International - UK
('University of Oxford', 'UK', NULL),
('University of Cambridge', 'UK', NULL),
('Imperial College London', 'UK', NULL),
('London School of Economics', 'UK', NULL),
('University College London', 'UK', NULL),
('University of Edinburgh', 'UK', NULL),
('University of Manchester', 'UK', NULL),
('University of Warwick', 'UK', NULL),
('King''s College London', 'UK', NULL),

-- International - Canada
('University of Toronto', 'CA', 'ON'),
('McGill University', 'CA', 'QC'),
('University of British Columbia', 'CA', 'BC'),
('University of Waterloo', 'CA', 'ON'),
('Western University', 'CA', 'ON'),
('Queen''s University', 'CA', 'ON'),

-- International - Europe
('ETH Zurich', 'CH', NULL),
('EPFL', 'CH', NULL),
('HEC Paris', 'FR', NULL),
('INSEAD', 'FR', NULL),
('Bocconi University', 'IT', NULL),
('Technical University of Munich', 'DE', NULL),
('Ludwig Maximilian University of Munich', 'DE', NULL),

-- International - Asia
('National University of Singapore', 'SG', NULL),
('Nanyang Technological University', 'SG', NULL),
('University of Hong Kong', 'HK', NULL),
('Hong Kong University of Science and Technology', 'HK', NULL),
('Tsinghua University', 'CN', NULL),
('Peking University', 'CN', NULL),
('Fudan University', 'CN', NULL),
('Shanghai Jiao Tong University', 'CN', NULL),
('University of Tokyo', 'JP', NULL),
('Kyoto University', 'JP', NULL),
('Seoul National University', 'KR', NULL),
('KAIST', 'KR', NULL),
('Indian Institute of Technology Bombay', 'IN', NULL),
('Indian Institute of Technology Delhi', 'IN', NULL),
('Indian Institute of Technology Kanpur', 'IN', NULL),
('Indian Institute of Technology Madras', 'IN', NULL),

-- International - Australia
('University of Melbourne', 'AU', 'VIC'),
('University of Sydney', 'AU', 'NSW'),
('Australian National University', 'AU', 'ACT'),
('University of New South Wales', 'AU', 'NSW'),
('University of Queensland', 'AU', 'QLD'),
('Monash University', 'AU', 'VIC'),

-- Other entry for unlisted schools
('Other (please specify in message)', 'OTHER', NULL)

ON CONFLICT (name) DO NOTHING;
